# Site settings
title: Ken's Learning Process
header-img: img/home-bg.png
email: madifana@yahoo.com
copyright_name: madifana
description: > # this means to ignore newlines until "baseurl:"
  Gaining a deeper understanding through teaching.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  madifana
learn_profile: madifana
email_username: madifana@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
